### ISSUE TITLE
Current boot configuration will break if `php artisan config:cache` is run

### ISSUE THREAD

**Issue by damianed** [Shopify/shopify-app-template-php#123]
# Issue summary
The current [Context initialization](https://github.com/Shopify/shopify-app-php/blob/main/app/Providers/AppServiceProvider.php#L33-L38) access env variables directly, this is not advised by the [laravel documentation](https://laravel.com/docs/9.x/configuration#configuration-caching) since after `php artisan config:cache` (a command normally run when deploying to production) the env file is never loaded.
## Expected behavior

This environment variables should be added to a config file and by accessed using the [config helper](https://laravel.com/docs/9.x/configuration#accessing-configuration-values)

## Actual behavior
if you run `php artisan config:cache` the app will start throwing an error

<details>
Shopify\Context::initialize(): Argument #1 ($apiKey) must be of type string, null given, called in /home/damiane/shopify-app-php/app/Providers/AppServiceProvider.php on line 38

  at vendor/shopify/shopify-api/src/Context.php:66
     62▕      *                                                              it
     63▕      *
     64▕      * @throws \Shopify\Exception\MissingArgumentException
     65▕      */
  ➜  66▕     public static function initialize(
     67▕         string $apiKey,
     68▕         string $apiSecretKey,
     69▕         $scopes,
     70▕         string $hostName,

  1   app/Providers/AppServiceProvider.php:38
      Shopify\Context::initialize()

      +7 vendor frames 
  9   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
</details>

## Steps to reproduce the problem

1. Run `php artisan config:cache`
1. run `php artisan serve`
---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by Sanjay-100** [comment]
@damianed 
I am not able to   reproduce the problem
`Run php artisan config:cache
run php artisan serve
`

can you please provide me with all setups on my setup project both are working fine?

**Comment by greatwitenorth** [comment]
I found the exact same issue today. I had to replace all the uses of `env` to config, then move the env calls to the appropriate config files. This is directly from [Laravel's website](https://laravel.com/docs/9.x/configuration#configuration-caching):

_If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded; therefore, the env function will only return external, system level environment variables._

The only fix without code changes is to not use config:cache.
