### ISSUE TITLE
Install script not working 

### ISSUE THREAD

**Issue by Sanjay-100** [Shopify/shopify-app-template-php#152]
# Issue summary

unable to run code - 
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal 3.3.3 -> satisfiable by doctrine/dbal[3.3.3].
    - doctrine/dbal 3.3.3 requires composer-runtime-api ^2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?   app code run properly

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. shopifi CLI $  shopify app create php
2.  composer install
3. 

 
## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hi @Sanjay-100. Based on the error message, it seems like you might be using `composer` v1, when this requires composer v2. Could you please:

1. Confirm which version you're using?
2. If it is v1, does it still fail if you upgrade to v2?

**Comment by mveer08** [comment]
@Sanjay-100 Shopify php app template is based on Laravel 8 version and you need to have Composer version 2 and above.
