### ISSUE TITLE
App thinks it's installed even though the OAuth process didn't finish

### ISSUE THREAD

**Issue by theCapypara** [Shopify/shopify-app-template-php#235]
# Issue summary
When installing the app with `app create` and then starting the Oauth process but aborting it, the app incorrectly assumes it's still installed. When trying to install again it won't redirect to `/login`. This also happens when uninstalling the app in a shop and installing it again.

## Expected behavior
It should redirect to `/login` and begin the oauth process.

## Actual behavior
See issue summary.

## Steps to reproduce the problem
1. Create the app and serve it with Shopify CLI
2. Begin the app installation
3. Abort the installation
4. Try again

## Reduced test case
n/a

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
The PR that fixes this issue was merged today, thanks for your help!
