### ISSUE TITLE
Accessing environment variable from the components

### ISSUE THREAD

**Issue by itsazzad** [Shopify/shopify-app-template-php#338]
# Issue summary

Failing to get environment variables from components after creating a new app from https://github.com/Shopify/shopify-app-template-php/tree/cli_three#setting-up-your-laravel-app.
Neither of the prefixes is working:
```env
PUBLIC_MY_API_URL="example.com"
VITE_SOME_KEY=123
VITE_APP_TITLE="My App"
SHOPIFY_APP_XYZ="My App"
```

## Expected behavior

With `process.env.` or `import.meta.env.` should return the environment variables.

## Actual behavior

It is just returning undefined.

## Steps to reproduce the problem

1. Set environment variables in either or both of `/.env` and `/web/.env`
2. Run the server with `npm run dev`
3. Open the webpage with NGROK URL 
4. Check the environment variable in any component.

## Reduced test case

---

## Checklist

- [x ] I have described this issue in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
> 4. Check the environment variable in any component.

Where are you checking the environment variables? The examples given (`process.env.` and `import.meta.env.`) are JavaScript specific, even though this app back-end is PHP.

**Comment by itsazzad** [comment]
@mkevinosullivan I am in need to have environment variables to be read in /web/frontend/pages/index.jsx
How can I?

**Comment by mkevinosullivan** [comment]
Creating a `.env` file in `web/frontend` and prefixing the environment variable with `VITE_` should make it available in your FE code via `import.meta.env.`

**Comment by mkevinosullivan** [comment]
@itsazzad Thanks for letting me know that it's working for you.

Given that the backend runs from `web` and the frontend runs from `web/frontend`, symlinking would seem like the easiest solution for using the same `.env` file.
