### ISSUE TITLE
 npm init @shopify/app@latest --template php command failed

### ISSUE THREAD

**Issue by bhattnishant** [Shopify/shopify-app-template-php#366]
# Issue summary

Error while setup template / command failed
 npm init @shopify/app@latest --template php

## Expected behavior

it should install template

## Actual behavior

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Unexpected argument: php                                                    │
│  See more help with --help                                                   │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

**Comment by mikespook** [comment]
You need to add extra "--" in front of "--template php".

From
`npm init @shopify/app@latest --template php` 
to
`npm init @shopify/app@latest -- --template php`
