### ISSUE TITLE
deploy in production Auth guard [] is not defined

### ISSUE THREAD

**Issue by meltinbit** [Shopify/shopify-app-template-php#414]
# when I deploy the app in production I get Auth guard[] is not defined

The app works well in dev mode. In production it seems that the commented guards in config/auth.php are causing the problem.
I tried to deploy on Laravel Forge and also i setup a custom Ubuntu on Digital Ocean and i got the same error.

![Screenshot 2023-01-18 at 22 02 32](https://user-images.githubusercontent.com/24719939/213293929-7ea65471-287d-4c06-a37d-948ae43a317b.png)

**Comment by morbillius** [comment]
How did you solve this problem?
