### ISSUE TITLE
OAuth Session could not be saved. Please check your session storage functionality.

### ISSUE THREAD

**Issue by airarm** [Shopify/shopify-app-template-php#426]
Hi everyone, I create php app use shopify cli v3

Request to get access token is working in code but sesstion save to db return false 

[https://www.screencast.com/t/7n73Xir6](https://www.screencast.com/t/7n73Xir6)

and shows up error

[https://www.screencast.com/t/AIZikeEg](https://www.screencast.com/t/AIZikeEg)

Please help guys

**Comment by MaxSamnani** [comment]
What is the solution of this issue?
