### ISSUE TITLE
Im using cli of shopify to install my app, laravel and react js ,how can depoy on herooku this shopify-app-template-php

### ISSUE THREAD

**Issue by Lahoucine-hrird** [Shopify/shopify-app-template-php#468]
# Issue summary

Write a short description of the issue here ↓

[Im using cli of shopify to install my app, laravel and react js ,how can depoy on herooku this shopify-app-template-php](https://stackoverflow.com/questions/77045691/im-using-cli-of-shopify-to-install-my-app-laravel-and-react-js-how-can-depoy)
## Expected behavior

Errors

-----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. heroku/nodejs
       2. heroku/php
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 18.x...
       Downloading and installing node 18.17.1...
       Using default npm version: 9.6.7
       
-----> Installing dependencies
       Installing node modules
       
       added 780 packages, and audited 782 packages in 12s
       
       146 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       npm notice 
       npm notice New major version of npm available! 9.6.7 -> 10.0.0
       npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.0.0>
       npm notice Run `npm install -g npm@10.0.0` to update!
       npm notice 
       
-----> Build
       Running build
       
       > applesting@1.0.0 build
       > shopify app build
       
── external error ───────────────────���──────────────────────────────────────────
Error coming from `composer build`
Command failed with ENOENT: composer build
spawn composer ENOENT
────────────────────────────────────────────────────────────────────────────────
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by NomanHameed** [comment]
Deploy on heroku follow heroku documentation on Building Docker Images with heroku.yml.

[Building Docker Images with heroku.yml](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml)

if still face issues feel free to ask.
thanks

**Comment by Lahoucine-hrird** [comment]
C:\laragon\www\applesting2\web(main -> heroku)                                 
λ git push heroku main                                                         
Enumerating objects: 11, done.                                                 
Counting objects: 100% (11/11), done.                                          
Delta compression using up to 8 threads                                        
Compressing objects: 100% (7/7), done.                                         
Writing objects: 100% (7/7), 798 bytes | 798.00 KiB/s, done.                   
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0                           
remote: Updated 11076 paths from 6d3fe65c                                      
remote: Compressing source files... done.                                      
remote: Building source:                                                       
remote:                                                                        
remote: -----> Building on the Heroku-22 stack                                 
remote: -----> Using buildpacks:                                               
remote:        1. heroku/nodejs                                                
remote:        2. heroku/php                                                   
remote: -----> Node.js app detected                                            
remote:                                                                        
remote: -----> Creating runtime environment                                    
remote:                                                                        
remote:        NPM_CONFIG_PRODUCTION=true                                      
remote:        NPM_CONFIG_LOGLEVEL=error                                       
remote:        USE_NPM_INSTALL=true                                            
remote:        NODE_VERBOSE=false                                              
remote:        NODE_ENV=production                                             
remote:        NODE_MODULES_CACHE=false                                        
remote:                                                                        
remote: -----> Installing binaries                                             
remote:        engines.node (package.json):  unspecified                       
remote:        engines.npm (package.json):   8.15.0                            
remote:                                                                        
remote:        Resolving node version 18.x...                                  
remote:        Downloading and installing node 18.17.1...                      
remote:        Bootstrapping npm 8.15.0 (replacing 9.6.7)...                   
remote:        npm 8.15.0 installed                                            
remote:                                                                        
remote: -----> Restoring cache                                                 
remote:        Caching has been disabled because NODE_MODULES_CACHE=false      
remote:                                                                        
remote: -----> Installing dependencies                                         
remote:        Installing node modules (package.json + package-lock)           
remote:                                                                        
remote:        added 513 packages, and audited 515 packages in 7s              
remote:                                                                        
remote:        106 packages are looking for funding                            
remote:          run `npm fund` for details                                    
remote:                                                                        
remote:        found 0 vulnerabilities                                         
remote:                                                                        
remote: -----> Build                                                           
remote:        Detected both "build" and "heroku-postbuild" scripts            
remote:        Running heroku-postbuild                                        
remote:                                                                        
remote:        > applesting@1.0.0 heroku-postbuild                             
remote:        > npm install && npm run build                                  
remote:                                                                        
remote:                                                                        
remote:        up to date, audited 515 packages in 1s                          
remote:                                                                        
remote:        106 packages are looking for funding                            
remote:          run `npm fund` for details                                    
remote:                                                                        
remote:        found 0 vulnerabilities                                         
remote:                                                                        
remote:        > applesting@1.0.0 build                                        
remote:        > shopify app build                                             
remote:                                                                        
remote: ── external error ─────────────────────────────────────────────────────
remote:                                                                        
remote: Error coming from `composer build`                                     
remote:                                                                        
remote: Command failed with ENOENT: composer build                             
remote: spawn composer ENOENT                                                  
remote:                                                                        
remote: ───────────────────────────────────────────────────────────────────────
remote:                                                                        
remote:                                                                        
remote: -----> Build failed                                                    
remote:                                                                        
remote:        We're sorry this build is failing! You can troubleshoot common i
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deplo
remote:                                                                        
remote:        Some possible problems:                                         
remote:                                                                        
remote:        - Node version not specified in package.json                    
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifyin
remote:                                                                        
remote:        Love,                                                           
remote:        Heroku                                                          
remote:                                                                        
remote:  !     Push rejected, failed to compile Node.js app.                   
remote:                                                                        
remote:  !     Push failed                                                     
remote: Verifying deploy...                                                    
remote:                                                                        
remote: !       Push rejected to shopify-app25.                                
remote:                                                                        
To https://git.heroku.com/shopify-app25.git                                    
 ! [remote rejected]   main -> main (pre-receive hook declined)                
error: failed to push some refs to 'https://git.heroku.com/shopify-app25.git'

**Comment by Lahoucine-hrird** [comment]
I'm using sqlite,in storage folder

**Comment by Lahoucine-hrird** [comment]
yes is lasted template version,I'm using sqlite,in storage folder,Do I need to reinstall this heroku-release.sh in the web folder
Directory structure
└── <App name>
    ├── shopify.app.toml
    ├── package.json
    ├── node_modules/
    |   └── ...
    ├── web/
    |   ├── composer.lock
    |   ├──  frontend/
    |   ├──  public/
    |   ├──  composer.json
    |   ├──  Dockerfile
    |   ├── shopify.web.toml
    |   └── ...
    ├── extensions/
    |   ├── my-ui-extension
    |   |  ├── shopify.extension.toml
    |   |  ├── package.json
    |   |  └── ...
    |   ├── my-function-extension
    |   |  ├── shopify.extension.toml
    |   |  ├── package.json
    |   |  └── ...
    |   ├── my-theme-extension
    |   |  ├── shopify.extension.toml
    |   |  ├── package.json
    |   |  └── ...
    |   └── ...
    └── .env

**Comment by Lahoucine-hrird** [comment]
-----> Using buildpacks:
1. heroku/nodejs
2. heroku/php

**Comment by rafaelstz** [comment]
@Lahoucine-hrird you won't need the `heroku-release.sh`. However, you will need to have the `heroku.yml` in your root folder and migrate from **buildpacks to Docker**.

**Comment by Lahoucine-hrird** [comment]
Illuminate\Database\QueryException
could not find driver (SQL: select exists(select * from "sessions" where "shop" = myshop.myshopify.com and "access_token" is not null) as "exists")
